version: '3.8'

services:
  web:
    build: .
    command: gunicorn aslmovi.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_folder:/app/static
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=aslmovi
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_folder:/app/static
    depends_on:
      - web


volumes:
  postgres_data:
  static_folder: