# Generated by Django 5.0 on 2024-01-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('janr', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=50)),
                ('voice', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=255)),
                ('picture', models.TextField()),
                ('download', models.TextField()),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
