name: Aslmovi
on:
  push:
    branches:
      - main
      - master

jobs:
  first:
    name: Install Ubuntu
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: aslmovi
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Update
        run: sudo apt update
      - name: check out repo
        uses: actions/checkout@v3
      - name: Install python 3-pip
        run: sudo apt install python3-pip
      - name: Requirements install
        run: pip install -r requirements.txt
      - name: Run test
        env:
          DJANGO_SETTINGS_MODULE: aslmovi.settings.local
          SECRET_KEY: django-insecure-7m04k$2imt91b!d&gnk%gk)p(2%)w9@@w=h1ukubzc&cqgrakg
          SQL_ENGINE: django.db.backends.postgresql_psycopg2
          SQL_DATABASE: aslmovi
          SQL_USER: postgres
          SQL_PASSWORD: 12345
          SQL_HOST: localhost
          SQL_PORT: 5432
        run:
          python manage.py migrate
          python manage.py test